### ISSUE TITLE
how to printout the IR for learning purposes?

### ISSUE THREAD

**Issue by shi-yan** [sunfishcode/simplejit-demo#55]
I want to learn from the generated IR, how can I print it out?

Thanks

**Comment by bjorn3** [comment]
Adding `println!("{}", self.ctx.func)` here

https://github.com/bytecodealliance/cranelift-jit-demo/blob/e120e20ebf410597b6973551229fec029506192e/src/jit.rs#L49

should work I think.

**Comment by shi-yan** [comment]
it did work. Thanks!
