### ISSUE TITLE
Demo also runs in Windows

### ISSUE THREAD

**Issue by sophiajt** [sunfishcode/simplejit-demo#6]
I removed the assert to see that the demo does work in Windows. I haven't dug in further to see why it works, but figured I'd share.

**Comment by skyne98** [comment]
I think that the limitation described there is not true any more.

**Comment by aleksmelnikov** [comment]
I commented this code in the demo:
```
 // Windows calling conventions are not supported yet.
 //       if cfg!(windows) {
 //          unimplemented!();
// }
```
Then I successful compiled the demo on linux for windows target:
`cargo build --release --target x86_64-pc-windows-gnu`

Then I could successful run the demo binary on Windows 10.
