### ISSUE TITLE
Is there a way to view the JIT compiled code?

### ISSUE THREAD

**Issue by sunjay** [sunfishcode/simplejit-demo#67]
I know you can print the cranelift IR with `ctx.func` (#55), but is there a way to print the generated x86 instructions before or after [the `module.finalize_definitions()` line](https://github.com/bytecodealliance/cranelift-jit-demo/blob/main/src/jit.rs#L81)? I want to see the final code that gets generated so I can debug issues with it and perhaps optimize the IR I'm generating.

Thanks!

**Comment by cfallin** [comment]
Hi @sunjay -- if you run with `RUST_LOG=trace` you will see disassemblies of generated function bodies in the trace output (grep for "disassembly").

Or, programmatically, [the `mach_compile_result` on the `Context`](https://github.com/bytecodealliance/wasmtime/blob/f1b821e16fd9cd974d2e27122838d5ea44cd65af/cranelift/codegen/src/context.rs#L54), if you call [`.set_disasm(true)`](https://github.com/bytecodealliance/wasmtime/blob/f1b821e16fd9cd974d2e27122838d5ea44cd65af/cranelift/codegen/src/context.rs#L96), has a [`disasm` field](https://github.com/bytecodealliance/wasmtime/blob/f1b821e16fd9cd974d2e27122838d5ea44cd65af/cranelift/codegen/src/machinst/mod.rs#L281) that will give you the disassembly as a string.

Hope that helps! I'll go ahead and close this with the question answered but feel free to stop by our [Zulip](https://bytecodealliance.zulipchat.com/) with any other questions.

**Comment by cfallin** [comment]
Ah, and I'll note that the above discussion is at the level of the `Context` API in `cranelift-codegen`; I'm not completely sure how much is wired through to `cranelift-jit-demo`'s public API, but anything that is missing could certainly be added via PR if you're willing.

**Comment by sunjay** [comment]
That's exactly what I needed! Thanks @cfallin! My code is based on `cranelift-jit-demo`, but I'm not using it directly so the `mach_compile_result` and `disasm` field were exactly what I was looking for. Thanks again!
