### ISSUE TITLE
How to call a function written by Rust?

### ISSUE THREAD

**Issue by leejingbo** [sunfishcode/simplejit-demo#9]
Toy lang can call puts function in libc. How to call a function writen by Rust? 

Thanks a lot!

**Comment by sunfishcode** [comment]
The easiest way to do it is to make a Rust function which is `extern "C"` and `#[no_mangle]`, and then you can call it in the same way as `puts`.

**Comment by bjorn3** [comment]
Another way is to use [`symbol`](https://github.com/CraneStation/cranelift/blob/9b689eb8ed45373988db5f593876a5034b3291f1/cranelift-simplejit/src/backend.rs#L83) on the builder to make a function available for use to the jitted code. You need to pass the name and the function pointer casted to `*const u8` to that method.

**Comment by leejingbo** [comment]
@sunfishcode @bjorn3  Thank you for your answer!
